config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from config import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('markdownx/', include('markdownx.urls')),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")), 
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns +=  i18n_patterns(path('admin/', admin.site.urls),)

else:
    urlpatterns +=  i18n_patterns(
        path('admin-zone/', admin.site.urls),
        )

core/urls.py
from django.urls import path
from django.conf.urls.static import static
from config import settings
from .views import (
    ArticleDetailView, 
    IndexView, 
    ContactView,
    articles_view,
    SearchView, 
    RecruitingView,
    AboutView,
    )

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('articles/', articles_view, name='articles'),
    path('article/<slug:slug>', ArticleDetailView.as_view(), name='articledetail'),
    path('contact', ContactView.as_view(), name='contact'),
    path('about', AboutView.as_view(), name='about'),
    path('recruiting', RecruitingView.as_view(), name='recruiting'),
    path('articles/search', SearchView.as_view(), name='search'),


]

core/models.py
from django.db import models
from tinymce import models as tinymce_models
from django.urls import reverse
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.text import slugify
from account.models import Profile 
from django.contrib.auth.models import User

# Create your models here.
JOB_TYPE_CHOICES = (
    ("FULLTIME", _("دوام كامل")),     
    ("PART_TIME", _("دوام جزئي")),
    ("INTERNSHIP", _("فترة تدريبية")),
    ("TEMPORARY", _("مؤقت")),
)
class AbstractSEO(models.Model):
    meta_title       = models.CharField(max_length=70, verbose_name="titre meta", blank=True, null=True)
    meta_description = models.TextField(verbose_name="description meta", blank=True, null=True)
    meta_keyword     = models.CharField(max_length=150, verbose_name="Keywords meta", blank=True, null=True)  
    class Meta:
        abstract =True

class Issue(AbstractSEO,models.Model):
    title              = models.CharField(max_length=254, verbose_name="Titre du Numéro")
    slug               = models.SlugField()
    actif              = models.BooleanField(verbose_name='actif', default=True)
    cover_a            = models.ImageField(verbose_name="image de la couverture side A", blank=True, null=True)
    cover_b            = models.ImageField(verbose_name="image de la couverture side B", blank=True, null=True)
    pdf                = models.FileField(upload_to='media', verbose_name='pdf of the issue', null=True, blank=True)
    start_date         = models.DateTimeField(verbose_name='Date debut ',  auto_now_add=True)
    end_date           = models.DateTimeField(verbose_name='Date fin',  auto_now_add=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:issuedetail', kwargs={'pk': self.pk})

class Category(AbstractSEO, MPTTModel):
    name  = models.CharField( max_length=150, verbose_name='Nom')
    slug  = models.SlugField( max_length=150, unique= True, verbose_name='URL')
    order  = models.IntegerField(verbose_name='ordre', null=True, blank=True)
    actif = models.BooleanField(verbose_name='actif', default=True)
    to_home_page = models.BooleanField(verbose_name="ajouter a la page d'accueil", default=False)
    to_footer = models.BooleanField(verbose_name="ajouter au footer", default=False)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    created      = models.DateTimeField(verbose_name='Date de Création',  auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    def __str__(self):
        return self.name
    def save(self, *args, **kwargs):
        import random
        if not self.slug:
            self.slug = str(slugify(self.name) + "-" + slugify(int(random.randint(1, 10000)))
                    )
        super(Category, self).save(*args, **kwargs)  
    # def get_absolute_url(self):
    #     return reverse('core:articles', kwargs={'pk': self.pk})
    def get_absolute_url(self):
        return f"/articles/?category={self.id}"
    
    # def get_articles_of_author(self):
    #     return f"/articles/?author={self.id}"
    
    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = '- Catégories'
    class MPTTMeta:
        order_insertion_by = ["name"]

class Contact(models.Model):
    name        = models.CharField(verbose_name=_('Nom complet'), max_length=100)
    phone       = models.CharField(verbose_name=_("Téléphone") , max_length=25)
    email       = models.EmailField(verbose_name=_("Email"), null=True, blank =True)
    subject     = models.CharField(verbose_name=_("Sujet"), max_length=50, blank=True,null=True)
    message     = models.TextField(verbose_name=_("Message"), blank=True, null=True)
    date_sent   = models.DateTimeField(verbose_name=_("Date"), auto_now_add=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ('id',)
        verbose_name = 'Formulaire de contact'
        verbose_name_plural = 'Formulaire de contact'
class Tag(models.Model):
    name = models.CharField(max_length=50)
    is_active =  models.BooleanField(default=True)
    created         = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated         = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

class Hiring(models.Model):
    name        = models.CharField(max_length=150, verbose_name='Nom')
    email       = models.EmailField(verbose_name="E-mail", null=True, blank=True)
    phone       = models.CharField(verbose_name="Téléphone" , max_length=25)
    birth_date  = models.DateField(verbose_name='date de naissance',null=True, blank=True) 
    birth_place = models.CharField(max_length=150, verbose_name='lieu de naissance', null=True, blank=True)
    message     = models.TextField(verbose_name='experience', null=True, blank=True)
    cv_file     = models.FileField(upload_to='media', verbose_name='CV', null=True, blank=True)

    class Meta:
        verbose_name = _("Recrutement")
        verbose_name_plural = _("Recrutement")
    
    def __str__(self):
        return str(self.email)
  
class Job(models.Model):
    title       = models.CharField( verbose_name=_("job title"), max_length=150)
    slug        = models.SlugField()
    description = tinymce_models.HTMLField(verbose_name='experience', null=True, blank=True)
    type        = models.CharField(choices=JOB_TYPE_CHOICES, default="TEMPORARY",max_length= 20, verbose_name=_("Job type")) 
    tags        = models.ManyToManyField(Tag, verbose_name=_("tags"),  blank=True)
    budget      = models.DecimalField( max_digits=10, decimal_places=2, null=True, blank=True)
    duration    = models.IntegerField(verbose_name=_("Number of days"), null=True, blank=True)
    expiration  = models.DateField(blank=True, null=True)
    deadline    = models.DateField(blank=True, null=True)
    is_active   =  models.BooleanField(default=False)
    order       = models.IntegerField(verbose_name='ordre', null=True, blank=True)

    class Meta:
        verbose_name = _("Annonce")
        verbose_name_plural = _("Annonce")
    
    def __str__(self):
        return str(self.title)
    
class About(models.Model):
    name            = models.CharField(verbose_name="Nom de l'entreprise", max_length=100,  blank=True, null=True)
    image_high      = models.ImageField(upload_to='images/', verbose_name='image_1', blank=True, null=True)
    image_low       = models.ImageField(upload_to='images/', verbose_name="image_2", blank=True, null=True)
    title           = models.CharField(verbose_name="Titre", max_length=50, blank=True) 
    about_high      = tinymce_models.HTMLField(verbose_name='Text a propos', blank=True, null=True)
    about_low       = tinymce_models.HTMLField(verbose_name='Page a propos 2', blank=True, null=True)
 
    def __str__(self):
        return str(self.name)
    class Meta:
        verbose_name = 'about'
        verbose_name_plural = 'abouts'
        
class Article(AbstractSEO, models.Model):
    title         = models.CharField( max_length=150, verbose_name='Titre')
    slug          = models.SlugField()
    apercu        = models.CharField( max_length=300, verbose_name='apercu', blank=True, null=True)
    chapo         = models.CharField( max_length=300, verbose_name='chapô ',blank=True, null=True)
    quote         = models.CharField( max_length=300, verbose_name='phrase mise en avant ', blank=True, null=True)
    texte_top     = tinymce_models.HTMLField(verbose_name='texte haut', blank=True, null=True)
    texte_image  = tinymce_models.HTMLField(verbose_name='texte deux colonnes', blank=True, null=True)
    texte_bottom  = tinymce_models.HTMLField(verbose_name='texte bas', blank=True, null=True)
    authors       = models.ManyToManyField(Profile, verbose_name="Auteur", related_name="articles_of_authors", blank=True)
    category      = models.ForeignKey(Category,on_delete=models.CASCADE,  verbose_name="categorie de l'article", related_name="category_of_article")
    issue         = models.ForeignKey(Issue,on_delete=models.CASCADE,   related_name="issue_of_article", blank=True, null=True)
    publish       = models.BooleanField(default=True, verbose_name='Publier',)
    en_avant = models.BooleanField(verbose_name="mettre en avant a la page d'accueil", default=False)
    to_home_page = models.BooleanField(verbose_name="ajouter a la page d'accueil", default=False)
    actif         = models.BooleanField(default=True)
    date       = models.DateTimeField(verbose_name='Date de publication', blank=True, null=True  )
    created       = models.DateTimeField(verbose_name='Date de Création',  auto_now_add=True)
    updated       = models.DateTimeField(verbose_name='Date de dernière mise à jour',  auto_now=True)
    def __str__(self):
        return str(self.title)
    def get_absolute_url(self):
        return reverse("core:articledetail", kwargs={"slug": self.slug})

 
    @property
    def first_image(self):
        image = None
        try:
            image = self.photos.first().image.url
        except:
            pass
        return image

    @property
    def last_image(self):
        image = None
        try:
            if self.photos.count() > 1:
                image = self.photos.last().image.url
        except:
            pass
        return image

    @property
    def get_authors(self):
        return ",".join([author.username for author in self.authors.all()])
        
    # @property
    # def get_articles_of_author(self):
    #     return [print(article) for article in self.article.authors]

class ArticleImage(models.Model):
    article             = models.ForeignKey(Article, related_name="photos", on_delete=models.CASCADE, null=True, blank = True)
    title               = models.CharField(max_length=254,verbose_name="Titre de l'image'")

core/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    DetailView,
    ListView,
    UpdateView,
    DeleteView, 
    TemplateView,
    CreateView,
)
from django.utils.translation import gettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from business.models import Slide
from .models import Article,Category, Contact,Hiring, Job, About
from .forms import  ContactForm, HiringForm
from .filters import get_filtered_articles
from django.core.paginator import Paginator
from account.models import Profile
from django.db.models import Q
from django.contrib import messages

# Create your views here.

########## HOMEPAGE ##########
class IndexView(ListView):
    model = Article
    template_name = "index.html"

    paginate_by = 1


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sliders"]           = Slide.place.slider()
        context["homepage_articles"]            = Article.objects.filter(en_avant=True).order_by('-updated')
        context["homepage_article_list"]          = Article.objects.filter(to_home_page=True).order_by('-updated')
        context["homepage_card_articles"]          = Article.objects.filter(to_home_page=True).order_by('-updated') 
        return context

########## ARTICLE ##########

#### LIST #######
def articles_view(request):

    filtered_articles= get_filtered_articles(request)
    context = filtered_articles['context']
    queryset = filtered_articles['qs']
    articles = queryset.order_by('-updated')
    context['articles'] = articles
    context["homepage_article_list"]= Article.objects.filter(to_home_page=True).order_by('-updated')
    context["homepage_card_articles"]          = Article.objects.filter(to_home_page=True).order_by('-updated') 
    context["all_authors"] = Profile.objects.all()

    #start paginate
    paginator = Paginator(articles, 2)
    page_number = request.GET.get('page')
    get_copy = request.GET.copy()
    #SIDOU edit page:
    # page_obj = paginator.get_page(page_number)

    # context = {'articles': page_obj, }
    # authrs = Profile.objects.all().values_list('id')
    # print("The authors: ========> ", authrs)


    try:
        context['articles'] = paginator.page(page_number)
    except PageNotAnInteger:
        context['articles'] = paginator.page(1)
    except EmptyPage:
        context['articles'] = paginator.page(paginator.num_pages)
    parameters = get_copy.pop('page', True) and get_copy.urlencode()
    context['parameters'] = parameters
    return render(request, 'articles.html', context)

######### DETAIL ##########
class ArticleDetailView(DetailView):
    template_name = "article_detail.html"
    model = Article 
    def get_context_data(self,  *args, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(*args,**kwargs)
        article = self.get_object()
        category = article.category
        articles =  Article.objects.filter(category=category, publish=True)
        context["related_articles"] = articles.exclude(id= article.id).order_by('?')[:8]
        context["categories"] = Category.objects.all()
        # context["article_categories"] = get_filtered_articles
        return context
##ABOUT
class AboutView(TemplateView):
    template_name= "about.html"
    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context["abouts"] =About.objects.all()
        return context
########## CONTACT ##########
class ContactView(SuccessMessageMixin, CreateView):
    template_name= "contact.html"
    form_class= ContactForm
    model = Contact 
    success_message = "تم استلام رسالتك ، شكرا لك"
    success_url = reverse_lazy('core:contact')
    def form_valid(self, form):
        try: 
            form.send_email() 
        except: 
            pass
        return super().form_valid(form)
    

########## Search ##########

class SearchView(ListView):
    model = Article
    template_name = "search.html"
    paginate_by = 8

    def get_queryset(self):  # new
        query = self.request.GET.get("search")
        
        object_list = Article.objects.filter(
            Q(title__icontains=query) | Q(apercu__icontains=query)| Q(chapo__icontains=query)| Q(quote__icontains=query)|
            Q(category__name__icontains=query) | Q(authors__username__icontains=query) | Q(texte_image__icontains=query)
        )
        return object_list
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["homepage_articles"]            = Article.objects.filter(en_avant=True).order_by('-updated')
        context["homepage_article_list"]          = Article.objects.filter(to_home_page=True).order_by('-updated')
        context["homepage_card_articles"]          = Article.objects.filter(to_home_page=True).order_by('-updated') 
        return context
########## recrutements ##########
class RecruitingView(SuccessMessageMixin, CreateView):
    template_name= "recrutement.html"
    form_class= HiringForm
    model = Hiring 
    success_message = "تم إرسال النموذج بنجاح" 
    success_url = reverse_lazy('core:recruiting')

    # def form_valid(self,request, form):
    #     messages.success(request, _("تم إرسال النموذج بنجاح "), extra_tags="toastr")
    #     return redirect('core:recruiting')

    def form_invalid(self, form):
        messages.error(self.request,form.errors)
        return redirect('core:recruiting') 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["jobs"] = Job.objects.filter(is_active=True).order_by('order')
        return context

core/templates/about.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}

 <!--Page Title-->
 <section class="page-title" style="background-image:url({% static 'images/background/5.png' %}); transform: scaleX(-1);">
	<div class="auto-container">
		<h2>معلومات عنا</h2>
		<ul class="page-breadcrumb" dir="rtl">
			<li class="page-breadcrumb" dir="rtl">معلومات عنا  </li>
			<li dir="rtl"><a href="{% url 'core:index' %}">الرئيسية</a></li>
		</ul>
	</div>
</section>
<!--End Page Title-->
{% for about  in  abouts %}
	<section class="story-section">
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- Content Column -->
				<div class="content-column col-lg-8 col-md-12 col-sm-12">
					<div class="inner-column">
						<p style="color:#242424;">{{about.about_high|safe}} </p>
					</div>
				</div>
				<!-- Image Column -->
				<div class="image-column col-lg-4 col-md-12 col-sm-12">
					<div class="inner-column">
						<div class="image">
							<img src="{{about.image_high.url}}" alt="" style="margin-top:40px;" /> 
					</div>
				</div>
				
			</div>
		</div>
	</section>
	
    <section class="mission-section" >
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- Image Column -->
				<div class="image-column col-xl-3 col-lg-4 col-md-12 col-sm-12">
					<div class="inner-column">
						<div class="image mt-3">
                            <img src="{{about.image_low.url}}" alt="{{business.name}}" />
						</div>
					</div>
				</div>
				
				<!-- Content Column -->
				<div class="content-column col-xl-9 col-lg-8 col-md-12 col-sm-12">
					<div class="inner-column">
					{{about.about_low|safe}}
					</div>
				</div>
			</div>
		</div>
	</section>

	
{% endfor %}
{% endblock content %}

core/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}

 <!--Page Title-->
	<section class="page-title" style="background-image:url({% static 'images/background/5.png' %}); transform: scaleX(-1);">
		<div class="auto-container">
			<h2>اتصل بنا</h2>
			<ul class="page-breadcrumb" dir="rtl">
				<li class="page-breadcrumb" dir="rtl"> اتصل بنا</li>
				<li dir="rtl"><a href="{% url 'core:index' %}">الرئيسية</a></li>
			</ul>
		</div>
	</section>
    <!--End Page Title-->
	
	<!-- Contact Form Section -->
	<section class="contact-form-section">
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title">
				<h2>اتصل بنا</h2>
				<div class="text"> <p style="color:#1B2845;"> يرجى ترك رسالة لنا باستخدام النموذج أدناه ، وسوف نتصل بك في أقرب وقت ممكن. </p> </div>
			</div>
			<div class="ol-lg-6 col-md-6 col-sm-12">
						
				<div id="messageQuote">
					{% include 'snippets/message.html' %}
					
				</div> 
			</div>
			<div class="row clearfix">
				
				<!-- Form Column -->
				<div class="form-column col-lg-12 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<!-- Contact Form -->
						<div class="contact-form">
								
							<!--Contact Form-->
							<form method="post" action="{% url 'core:contact' %}" >
								{% csrf_token %}
								<div class="row clearfix">
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="text" name="phone" id="id_phone"  placeholder="{% trans 'رقم الهاتف +213*' %}" pattern="^(?:0|\(?\+213\)?\s?|00213\s?)[1-79](?:[\.\-\s]?\d\d){4}$" required>
									</div>
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="text" name="name" id="id_name" placeholder="{% trans 'الإسم واللقب*' %}" required>
									</div>
									
									<div class="form-group col-lg-12 col-md-6 col-sm-12">
										<input type="text" name="email" id="id_email"  placeholder="{% trans 'بريد إلكتروني *' %}" required>
									</div>
									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<input type="text" name="subject" id="id_subject"  placeholder="{% trans 'موضوع *' %}" required>
									</div>
									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<textarea name="message" id="id_message"  placeholder="{% trans 'رسالة *' %}"></textarea>
									</div>
										<input type="text" name="username" id="username" hidden="true" >

									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<button class="theme-btn btn-style-one" type="submit" ><span class="txt" style="color:#fff;">{% trans "إرسال" %}</span></button>
									</div>
									
								</div>
							</form>
						</div>
					
					</div>
				</div>
				   
				<!-- Info Column -->
				{% comment %} <div class="info-column col-lg-5 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<!-- Contact Info List -->
						<ul class="contact-info-list">
							<li><strong>{% trans 'Adresse :' %}</strong><br>{{business.adress}}</li>
							<li><strong>{% trans "Adresse" %} :</strong><br>{% trans "Centre commercial et d'affaire Mohammadia mall 16000 Alger, Algérie" %}</li>
						</ul>
						<!-- Contact Info List -->
						<ul class="contact-info-list">
							<li><strong>{% trans "الهاتف" %} : </strong><a href="tel:{{business.phone}}" dir="ltr">{{business.phone}}</a></li>
							<li><strong>{% trans "بريد إلكتروني " %}  : </strong><a href="mailto:{{business.email}}" > {{business.email}}</a></li>
						</ul>
						<!-- Contact Info List -->
						<ul class="contact-info-list">
							<li><strong>{% trans "Horaires d'ouverture" %} :</strong><br>{% trans '08:00 AM - 16:30 PM' %} <br> {% trans 'DIMANCHE  – JEUDI'  %} </li>
						</ul>
						
					</div>
				</div> {% endcomment %}
				
			</div>
			
		</div>
	</section>
	<!-- End Contact Form Section -->
    	<!-- Map Section -->
        {% comment %} <section class="map-section">
            <div class="outer-container">
                <div class="map-outer">
                  
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d205078.93733318127!2d2.8658279251102634!3d36.569580306270424!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x128e53040eeba8c1%3A0x475724526b4ad2df!2sMarche%20de%20tapis%20mall!5e0!3m2!1sen!2sdz!4v1649753358673!5m2!1sen!2sdz" frameborder="0" style="border:0; width: 100%; height: 500px;" allowfullscreen   loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>            </div>

                   
                </div>
            </div>
        </section> {% endcomment %}
        <!-- End Map Section -->
{% endblock content %}

core/templates/recrutement.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
  
    <!--Page Title-->
	<section class="page-title" style="background-image:url({% static 'images/background/5.png' %}); transform: scaleX(-1);">
		<div class="auto-container">
			<h2> انضم إلينا</h2>
			<ul class="page-breadcrumb" dir="rtl">
				<li class="page-breadcrumb" dir="rtl"> انضم إلينا </li>
				<li dir="rtl"><a href="{% url 'core:index' %}">الرئيسية</a></li>
			</ul>
		</div>
	</section>
    <!--End Page Title-->  
	
    	<!-- Contact Form Section -->
	<section class="contact-form-section" style="background-image:url('images/background/contact.jpg' %})">
		<div class="auto-container">
			<!-- Sec Title -->
			{% include 'snippets/message.html' %}
			<div class="sec-title">
				<h2>{% trans 'انضم إلى فريقنا' %}</h2>
				<div class="text"> <p style="color:#242424;"> {% trans 'نحن نبحث دائمًا عن إضافة أعضاء جدد إلى فريقنا ، يرجى تقديم معلوماتك أدناه وسنتصل بك.' %}  </p></div>
			</div>

			<div class="row clearfix">
				
				<!-- Form Column -->
				<div class="form-column col-lg-6 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<!-- Contact Form -->
						<div class="contact-form">
								
							<!--Contact Form-->
							<form method="post" action="{% url 'core:recruiting' %}" enctype='multipart/form-data' >
								{% csrf_token %}
								<div class="row clearfix">
									<div class="form-group col-lg-12 col-md-6 col-sm-12">
										<input type="text" name="name" id="id_name" placeholder="{% trans 'الإسم واللقب*' %}" required>
									</div>
									
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="tel" name="phone" id="id_phone"  placeholder="{% trans 'رقم الهاتف +213*' %}" pattern="^(?:0|\(?\+213\)?\s?|00213\s?)[1-79](?:[\.\-\s]?\d\d){4}$" required>
									</div>
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="text" name="email" id="id_email"  placeholder="{% trans 'بريد إلكتروني *' %}" >
									</div>
									{% comment %} <div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="date" name="birth_date" id="id_birth_date"   placeholder="{% trans ' تاريخ الميلاد *' %}" required>
									</div> {% endcomment %}
                                    {% comment %} <div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="text" name="birth_place" id="id_birth_place"  placeholder="{% trans "Lieu de naissance *" %}" required>
									</div> {% endcomment %}
									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<textarea name="message" id="id_message"  placeholder="{% trans ' الخبرة' %}"></textarea>
									</div>
                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <input type="file" name="cv_file" id="id_cv_file"  placeholder="{% trans ' تحميل السيرة الذاتية *' %}">
									</div>
									<input type="text" name="username" id="username" hidden="true" >
									
									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<button class="theme-btn btn-style-one" type="submit" ><span class="txt"  style="color:#fff;">{% trans 'إرسال' %}</span></button>
									</div>
									
								</div>
							</form>
						</div>
					
					</div>
				</div>
				   
				<!-- Info Column -->
				<div class="info-column col-lg-6 col-md-12 col-sm-12">
					<div class="inner-column">
					{% for job in jobs %}
						<!-- Contact Info List -->
						<ul class="contact-info-list">
							<li> <h1 style="color:#000;">{{job.title}}</h1> </li>
							<li><strong> نوع الوظيفة </strong>{{job.get_type_display}}  &nbsp; <strong>ميزانية </strong>{{job.budget}} دج</li>
							<li> <strong>مدة </strong>{{job.duration}} يوم &nbsp; <strong>موعد التسليم </strong> {{job.deadline|date:'Y-m-d'}}</li>
							{{job.description|safe}}
						</ul>
					{% endfor %}
					</div>
				</div>
				
			</div>
			
		</div>
	</section>

{% endblock content %}