config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from config import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('markdownx/', include('markdownx.urls')),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")), 
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns +=  i18n_patterns(path('admin/', admin.site.urls),)

else:
    urlpatterns +=  i18n_patterns(
        path('admin-zone/', admin.site.urls),
        )

core/urls.py
from django.urls import path
from django.conf.urls.static import static
from config import settings
from .views import (
    ArticleDetailView, 
    IndexView, 
    ContactView,
    articles_view,
    SearchView, 
    RecruitingView,
    AboutView,
    )

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('articles/', articles_view, name='articles'),
    path('article/<slug:slug>', ArticleDetailView.as_view(), name='articledetail'),
    path('contact', ContactView.as_view(), name='contact'),
    path('about', AboutView.as_view(), name='about'),
    path('recruiting', RecruitingView.as_view(), name='recruiting'),
    path('articles/search', SearchView.as_view(), name='search'),


]

templates/base.html
{% load static %}
{% load mptt_tags %}

<!DOCTYPE html>
<html lang="ar">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


            <!-- Stylesheets -->
            {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> {% endcomment %}
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
            <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
            <link href="{% static 'css/style.css' %}" rel="stylesheet">
            <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

            {% comment %} owl CAROUSEL {% endcomment %}
            <link rel="stylesheet" href="{% static 'owlcarousel/owl.carousel.min.css' %}">
            <link rel="stylesheet" href="{% static 'owlcarousel/owl.theme.default.min.css' %}">

            <!-- Responsive -->
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
            <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
            <!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
            {% if business.favicon  %}
                <link rel="apple-touch-icon" sizes="180x180" href="{{business.favicon.url}}">
                <link rel="icon" type="image/png" sizes="32x32" href="{{business.favicon.url}}">
                <link rel="icon" type="image/png" sizes="16x16" href="{{business.favicon.url}}">
                <link rel="shortcut icon" href="{{business.favicon.url}}">
            {% endif %}

            {% block extra_seo %}
            <title>{{business.title}}</title>
            <meta name="keywords" content="{{business.meta_keyword}}">
            <meta name="description" content="{{business.meta_description}}">
            <meta name="author" content="{{business.name}}"  />
            <meta name="robots" content="index,follow" />
            <meta name="apple-mobile-web-app-title" content="{{business.title}}">
            <meta name="application-name" content="{{business.name}}">
            <meta property="og:url" content="" />
            <meta property="og:title" content="{{business.title}}" />
            <meta property="og:type" content="Services" />
            <meta property="og:site_name" content="{{business.name}} | {{business.title}}"/>
            {% endblock extra_seo %}
    </head>

    
    <body >
        <div class="page-wrapper">
            
            {% include "navbar.html" %}
            {% block content %}

        {% endblock content %}

        {% include "footer.html" %}
        </div>
        <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
            <script src="{% static 'js/jquery.js' %}"></script>
            <script src="{% static 'js/popper.min.js' %}"></script>
            <script src="{% static 'js/jquery-ui.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script src="{% static 'js/jquery.fancybox.js' %}"></script>
            <script src="{% static 'js/owl.js' %}"></script>
            <script src="{% static 'js/wow.js' %}"></script>
            <script src="{% static 'js/validate.js' %}"></script>
            <script src="{% static 'js/appear.js' %}"></script>
            <script src="{% static 'js/scrollbar.js' %}"></script>
            <script src="{% static 'js/script.js' %}"></script>

            {% comment %} owl CAROUSEL {% endcomment %}
            <script src="{% static 'jquery.min.js' %}"></script>
            <script src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>

            {% block script %}
            
            {% endblock script %}
    </body>
</html>

templates/footer.html
{% load static %}
  
  {% block content %}
  
        	<!-- Footer for index2-->
    <footer class="main-footer">
		<div class="auto-container">
        	<!--Widgets Section-->
            <div class="widgets-section">
            	<div class="row clearfix">
                	
                    <!--big column-->
                    <div class="big-column col-lg-6 col-md-12 col-sm-12">
                        <div class="row clearfix">
                        
                            <!--Footer Column-->
                            <div class="footer-column col-lg-7 col-md-6 col-sm-12">
                                <div class="footer-widget logo-widget">
									<div class="logo">
                                    	<a href="{% url 'core:index' %}">{% if business.logo_negatif %}<img src="{{business.logo_negatif.url}}" alt="" /></a>{% endif %}
                                    </div>
                                    {% if business.mini_about %}<div class="text"> {{business.mini_about}}</div>{% endif %}
                                    <ul class="social-icons">
										{% if business.linkedin %}
										<li><a href="{{business.linkedin}}"><img class="social-img" src="{% static 'images/icons/icons-linkedin-circled.svg' %}" alt=""></a></li>
										{% endif %}
										{% if business.facebook %}
										<li> <a href="{{business.facebook}}"><img class="social-img" src="{% static 'images/icons/icon-facebook-white.svg' %}" alt=""></a></li>
										{% endif %}
										{% if business.insta %}
										<li><a href="{{business.insta}}"><img class="social-img" src="{% static 'images/icons/icon-instagram-white.svg' %}" alt=""></a></li>
										{% endif %}
										{% if business.snapchat %}
										<li><a href="{{business.snapchat}}"><img class="social-img" src="{% static 'images/icons/icons-snapchat.svg' %}" alt=""></a></li>
										{% endif %}
										{% if business.tiktok %}
										<li><a href="{{business.tiktok}}"><img class="social-img" src="{% static 'images/icons/icons-tiktok.svg' %}" alt=""></a></li>
										{% endif %}
										{% if business.twitter %}
										<li><a href="{{business.twitter}}"><img class="social-img" src="{% static 'images/icons/icon-twitter-white.svg' %}" alt=""></a></li>
										{% endif %}
										{% if business.pinterest %}
										<li><a href="{{business.pinterest}}"><img class="social-img" src="{% static 'images/icons/icon-pinterest-white.svg' %}" alt=""></a></li>
										{% endif %}
										{% if business.youtube %}
										<li><a href="{{business.youtube}}"><img class="social-img" src="{% static 'images/icons/icon-youtube-white.svg' %}" alt=""></a></li>
										{% endif %}
                                    </ul>
								</div>
							</div>
							
							<!--Footer Column-->
                            <div class="footer-column col-lg-5 col-md-6 col-sm-12">
                                <div class="footer-widget links-widget">
                                	<h2>روابط أخرى</h2>
									<div class="widget-content">
										<ul class="list">
											<li><a href="{% url 'core:about'  %}"> معلومات عنا</a></li>
											{% for category in footer_categories  %}
                                        		<li><a href="{{category.get_absolute_url}}"> {{category.name}}</a></li>
											{% endfor %}
                                        </ul>
                                    </div>
								</div>
							</div>
						
						</div>
					</div>
					
					<!--big column-->
                    <div class="big-column col-lg-6 col-md-12 col-sm-12">
                        <div class="row clearfix">
                        
                            <!--Footer Column-->
                            <div class="footer-column col-lg-8 col-md-6 col-sm-12">
                                <div class="footer-widget contact-widget">
									<a href="{% url 'core:contact'  %}"><h2>  اتصل بنا  </h2></a>
									<div class="widget-content">
										<a dir="rtl" href="tel:1800-574-9687" class="contact-number">{{business.phone}}</a>
										<ul>
											<li>{{business.address}}</li>
											<li> <a href="mailto:{{business.email}}"> {{business.email}}</a> </li>
											<li><a href="{% url 'core:contact'  %}"  > نموذج الاتصال </a></li>
										</ul>

									</div>
								</div>
							</div>
							
							<!--Footer Column-->
                            {% comment %} <div class="footer-column col-lg-7 col-md-6 col-sm-12">
                                <div class="footer-widget newsletter-widget">
                                	<h2>Newsletter</h2>
									<div class="text">Get Special offers & Discounts</div>
									<!-- Newsletter Form -->
									<div class="newsletter-form">
										<form method="post" action="templateshub.net">
											<div class="form-group">
												<input type="email" name="email" value="" placeholder="Enter your email address" required>
												<button type="submit" class="theme-btn btn-style-one"><span class="txt">Subscribe</span></button>
											</div>
										</form>
									</div>
								</div>
							</div> {% endcomment %}
						
						</div>
					</div>
					
				</div>
			</div>
			
			<!--Footer Bottom-->
            <div class="footer-bottom clearfix">
                <div class="pull-left">
                    <div class="copyright">Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved {{business.name}} - Powered by <a  href="https://octopus-consulting.com" target="_blank">OCTOPUS CONSULTING</a></div>
                </div>
            </div>
			
		</div>
	</footer>
{% comment %} end Footer {% endcomment %}

    <!--Search Popup-->
<div id="search-popup" class="search-popup">
	<div class="close-search theme-btn"><span class="flaticon-cancel"></span></div>
	<div class="popup-inner">
		<div class="overlay-layer"></div>
    	<div class="search-form">
        	<form method="post" action="templateshub.net">
            	<div class="form-group">
                	<fieldset>
                        <input type="search" class="form-control" name="search-input" value="" placeholder="Search Here" required >
                        <input type="submit" value="Search Now!" class="theme-btn">
                    </fieldset>
                </div>
            </form>
            
            <br>
            {% comment %} <h3>Recent Search Keywords</h3> 
             <ul class="recent-searches">
                <li><a href="#">Home Interiors</a></li>
                <li><a href="#">Offices Interiors</a></li>
                <li><a href="#">Showroom Interiors</a></li>
                <li><a href="#">Building Interiors</a></li>
                <li><a href="#">Shops Interiors</a></li>
            </ul> {% endcomment %}
        
        </div>
        
    </div>
</div>

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-angle-up"></span></div>

  {% endblock content %}

templates/navbar.html
{% load static %}
{% load mptt_tags %}
{% block content %}
<header class="main-header header-style-one">
        <!--Header Top-->
        <div class="header-top">
            <div class="auto-container clearfix">
                <div class="top-left clearfix">
                    <div class="text">
                        {% if business.linkedin %}
                            <a href="{{business.linkedin}}"><img class="social-img" src="{% static 'images/icons/icons-linkedin-circled.svg' %}" alt=""></a>
                        {% endif %}
                        {% if business.facebook %}
                            <a href="{{business.facebook}}"><img class="social-img" src="{% static 'images/icons/icon-facebook-white.svg' %}" alt=""></a>
                        {% endif %}
                        {% if business.insta %}
                            <a href="{{business.insta}}"><img class="social-img" src="{% static 'images/icons/icon-instagram-white.svg' %}" alt=""></a>
                        {% endif %}
                        {% if business.snapchat %}
                            <a href="{{business.snapchat}}"><img class="social-img" src="{% static 'images/icons/icons-snapchat.svg' %}" alt=""></a>
                        {% endif %}
                        {% if business.tiktok %}
                            <a href="{{business.tiktok}}"><img class="social-img" src="{% static 'images/icons/icons-tiktok.svg' %}" alt=""></a>
                        {% endif %}
                        {% if business.twitter %}
                            <a href="{{business.twitter}}"><img class="social-img" src="{% static 'images/icons/icon-twitter-white.svg' %}" alt=""></a>
                        {% endif %}
                        {% if business.pinterest %}
                            <a href="{{business.pinterest}}"><img class="social-img" src="{% static 'images/icons/icon-pinterest-white.svg' %}" alt=""></a>
                        {% endif %}
                        {% if business.youtube %}
                            <a href="{{business.youtube}}"><img class="social-img" src="{% static 'images/icons/icon-youtube-white.svg' %}" alt=""></a>
                        {% endif %}
                    </div>
					
                </div>
                <div class="top-right clearfix">
                    <!-- Info List -->
					<ul class="info-list">
                        <li><a href="{% url 'core:contact'  %}" style="color: #E6AF2E;" >اتصل بنا </a></li>
						<li class="quote"><a href="{% url 'core:recruiting'  %}"> انضم إلينا</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Header Top -->

        <!-- Header Upper -->
        <div class="header-upper">
            <div class="inner-container">
                <div class="auto-container clearfix">
                    <!--Info-->
                    <div class="logo-outer">
                        <div class="logo "> <a href="{% url 'core:index' %}">{% if business.logo %}<img class="logo-img" src="{{business.logo.url}}" alt="" /></a>{% endif %}</div>
                    </div>

                    <!--Nav Box-->
                    <div class="nav-outer clearfix" >
                        <!--Mobile Navigation Toggler For Mobile--><div class="mobile-nav-toggler"><span class="icon flaticon-menu-1"></span></div>
                        <nav class="main-menu navbar-expand-md navbar-light">
                            <div class="navbar-header">
                                <!-- Togg le Button -->      
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="icon flaticon-menu-1"></span>
                                </button>
                            </div>
                            
                            <div class="collapse navbar-collapse clearfix" id="navbarSupportedContent" >
                                <ul class="navigation clearfix" dir="rtl">
                                    {% recursetree categories %}
                                        {% if not node.is_leaf_node %}
                                            {% if node.actif %}
                                                <li class="dropdown"><a href="{{node.get_absolute_url}}"> {{node.name}}</a>
                                                    <ul>
                                                        {% for sub_cat in node.children.all %}
                                                            {% if not sub_cat.is_leaf_node %}
                                                                <li class="dropdown"><a href="{{sub_cat.get_absolute_url}}"> {{sub_cat.name}}</a>
                                                                    <ul>
                                                                        {% for child in sub_cat.children.all %}
                                                                            <li><a href="{{child.get_absolute_url}}">  {{child.name}}</a></li>

                                                                            {% comment %} {% if  child.is_leaf_node %}
                                                                                <li><a href="{{child.get_absolute_url}}">  {{child.name}}</a></li>
                                                                            {% else %}
                                                                                <li class="dropdown" ><a href="{{sub_cat.get_absolute_url}}"> {{child.name}}</a>
                                                                                    <ul class="dropdown">
                                                                                        {% for gran_child in child.children.all %}
                                                                                            <li class="dropdown"><a href="{{child.get_absolute_url}}">  {{gran_child.name}}</a></li>
                                                                                        {% endfor %}
                                                                                    </ul>
                                                                                </li>
                                                                            {% endif %} {% endcomment %}
                                                                        {% endfor %}
                                                                    </ul>
                                                                </li>
                                                            {% else %}
                                                                <li><a href="{{sub_cat.get_absolute_url}}">  {{ sub_cat.name }}</a></li>
                                                            {% endif %}  
                                                            {% comment %} <li><a href="{{sub_cat.get_absolute_url}}">  {{ sub_cat.name }}</a></li> {% endcomment %}
                                                        {% endfor %}
                                                    </ul>
                                                </li>
                                            {% endif %} 
                                        {% else %}
                                            <li><a href="{{node.get_absolute_url}}">  {{node.name}}</a></li>
                                        {% endif %} 
                                    {% endrecursetree %}
                                    <li><a href="{% url 'core:index' %}"> الرئيسية</a></li>
                                </ul>

                            </div>
                        </nav>
                        <!-- Main Menu End-->

						<!-- Outer Box -->
                        <div class="outer-box clearfix">
                            <div class="search-box-btn"><span class="icon flaticon-magnifying-glass-1"></span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--End Header Upper-->

    	<!-- Mobile Menu  -->
        <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><span class="icon flaticon-cancel"></span></div>
            
            <nav class="menu-box">
                <div class="logo "style="position:relative;right: 60% !important" > <a href="{% url 'core:index' %}">{% if business.logo %}<img class="logo-img" src="{{business.logo.url}}" alt="" /></a>{% endif %}</div>
                <ul class="navigation clearfix"><!--Keep This Empty / Menu will come through Javascript--></ul>
				<!--Social Links-->
				<div class="social-links">
					<ul class="clearfix">
						{% if business.linkedin %}
                        <li><a href="{{business.linkedin}}"><img class="social-img" src="{% static 'images/icons/icons-linkedin-circled.svg' %}" alt=""></a></li>
                        {% endif %}
                        {% if business.facebook %}
                        <li> <a href="{{business.facebook}}"><img class="social-img" src="{% static 'images/icons/icon-facebook-white.svg' %}" alt=""></a></li>
                        {% endif %}
                        {% if business.insta %}
                        <li><a href="{{business.insta}}"><img class="social-img" src="{% static 'images/icons/icon-instagram-white.svg' %}" alt=""></a></li>
                        {% endif %}
                        {% if business.snapchat %}
                        <li><a href="{{business.snapchat}}"><img class="social-img" src="{% static 'images/icons/icons-snapchat.svg' %}" alt=""></a></li>
                        {% endif %}
                        {% if business.tiktok %}
                        <li><a href="{{business.tiktok}}"><img class="social-img" src="{% static 'images/icons/icons-tiktok.svg' %}" alt=""></a></li>
                        {% endif %}
                        {% if business.twitter %}
                        <li><a href="{{business.twitter}}"><img class="social-img" src="{% static 'images/icons/icon-twitter-white.svg' %}" alt=""></a></li>
                        {% endif %}
                        {% if business.pinterest %}
                        <li><a href="{{business.pinterest}}"><img class="social-img" src="{% static 'images/icons/icon-pinterest-white.svg' %}" alt=""></a></li>
                        {% endif %}
                        {% if business.youtube %}
                        <li><a href="{{business.youtube}}"><img class="social-img" src="{% static 'images/icons/icon-youtube-white.svg' %}" alt=""></a></li>
                        {% endif %}
					</ul>
                </div>
            </nav>
        </div><!-- End Mobile Menu -->

    </header>
{% endblock content %}